// Data kurikulum — dihasilkan dari sumber asli (dedup by judul+link).

export type TrackItem = {
  type: 'video' | 'resource' | 'task';
  label: string;
  url?: string | null;
  sub?: string;
};

export type Phase = {
  id: string;
  name: string;
  days?: [number, number];
  icon: string;
  desc: string;
  url?: string;
  items: TrackItem[];
};

export const CYBER_PHASES: Phase[] = [
  {
    id: "network",
    name: "Network+",
    days: [1, 7],
    icon: "🌐",
    desc: "Fondasi jaringan: OSI model, IP addressing, subnetting, routing, VLAN, wireless, troubleshooting.",
    items: [
      { type: "video", label: "How to Pass Your CompTIA N10-009 Network+ Exam", url: "https://www.youtube.com/watch?v=k7IOn3TiUc8", sub: "video" },
      { type: "video", label: "Understanding the OSI Model", url: "https://www.youtube.com/watch?v=AYgXr1dynKU", sub: "video" },
      { type: "video", label: "Networking Devices", url: "https://www.youtube.com/watch?v=iqjj4ZSPV08", sub: "video" },
      { type: "video", label: "Networking Functions", url: "https://www.youtube.com/watch?v=9uDpWfMbAdQ", sub: "video" },
      { type: "video", label: "Designing the Cloud", url: "https://www.youtube.com/watch?v=HzF7sg6Nx0c", sub: "video" },
      { type: "video", label: "Cloud Models", url: "https://www.youtube.com/watch?v=wI2x6eGF1Yg", sub: "video" },
      { type: "video", label: "Introduction to IP", url: "https://www.youtube.com/watch?v=ueth6WvFVMU", sub: "video" },
      { type: "video", label: "Common Ports", url: "https://www.youtube.com/watch?v=jX1pobYmZdE", sub: "video" },
      { type: "video", label: "Other Useful Protocols", url: "https://www.youtube.com/watch?v=5BahWbszVAY", sub: "video" },
      { type: "video", label: "Network Communication", url: "https://www.youtube.com/watch?v=9Vx-awO6qfc", sub: "video" },
      { type: "video", label: "Wireless Networking", url: "https://www.youtube.com/watch?v=NeTwL-040ds", sub: "video" },
      { type: "video", label: "Ethernet Standards", url: "https://www.youtube.com/watch?v=BxpRuARS56g", sub: "video" },
      { type: "video", label: "Optical Fiber", url: "https://www.youtube.com/watch?v=qLsNZSaj35E", sub: "video" },
      { type: "video", label: "Copper Cabling", url: "https://www.youtube.com/watch?v=zoefzxHIfPc", sub: "video" },
      { type: "video", label: "Network Transceivers", url: "https://www.youtube.com/watch?v=0aMmwkiuT0o", sub: "video" },
      { type: "video", label: "Fiber Connectors", url: "https://www.youtube.com/watch?v=PNoqhs5QvFw", sub: "video" },
      { type: "video", label: "Copper Connectors", url: "https://www.youtube.com/watch?v=Ca6rzoQm15w", sub: "video" },
      { type: "video", label: "Network Topologies", url: "https://www.youtube.com/watch?v=3ARTjvpZCoQ", sub: "video" },
      { type: "video", label: "Network Architectures", url: "https://www.youtube.com/watch?v=vVEL1LokboE", sub: "video" },
      { type: "video", label: "Binary Math", url: "https://www.youtube.com/watch?v=94dcHJfEAIo", sub: "video" },
      { type: "video", label: "IPv4 Addressing", url: "https://www.youtube.com/watch?v=JNNcyZ_VE2A", sub: "video" },
      { type: "video", label: "Classful Subnetting", url: "https://www.youtube.com/watch?v=XVIOtj-Z9m0", sub: "video" },
      { type: "video", label: "IPv4 Subnet Masks", url: "https://www.youtube.com/watch?v=p5NJ5Jt6oJo", sub: "video" },
      { type: "video", label: "Calculating IPv4 Subnets and Hosts", url: "https://www.youtube.com/watch?v=cYQOMifDlKI", sub: "video" },
      { type: "video", label: "Magic Number Subnetting", url: "https://www.youtube.com/watch?v=P1ROXMLjL04", sub: "video" },
      { type: "video", label: "Seven Second Subnetting", url: "https://www.youtube.com/watch?v=I3LBYMXBhus", sub: "video" },
      { type: "video", label: "Software Defined Networking", url: "https://www.youtube.com/watch?v=A6tPNGEfOzc", sub: "video" },
      { type: "video", label: "Virtual Extensible LAN", url: "https://www.youtube.com/watch?v=eBhqN6d6lRU", sub: "video" },
      { type: "video", label: "Zero Trust", url: "https://www.youtube.com/watch?v=jlMwWL4yalM", sub: "video" },
      { type: "video", label: "Infrastructure as Code", url: "https://www.youtube.com/watch?v=n6jIaKWixF4", sub: "video" },
      { type: "video", label: "IPv6 Addressing", url: "https://www.youtube.com/watch?v=CpLznUxkzg8", sub: "video" },
      { type: "video", label: "Static Routing", url: "https://www.youtube.com/watch?v=23a6_qexTvs", sub: "video" },
      { type: "video", label: "Dynamic Routing", url: "https://www.youtube.com/watch?v=YRZxshxI1xs", sub: "video" },
      { type: "video", label: "Routing Technologies", url: "https://www.youtube.com/watch?v=hU9bbmFhKxk", sub: "video" },
      { type: "video", label: "Network Address Translation", url: "https://www.youtube.com/watch?v=UILwCNOC5EI", sub: "video" },
      { type: "video", label: "VLANs and Trunking", url: "https://www.youtube.com/watch?v=ATbzbST_OIw", sub: "video" },
      { type: "video", label: "Interface Configurations", url: "https://www.youtube.com/watch?v=dno_MRp57UQ", sub: "video" },
      { type: "video", label: "Spanning Tree Protocol", url: "https://www.youtube.com/watch?v=Jm0BOz1Ur28", sub: "video" },
      { type: "video", label: "Wireless Technologies", url: "https://www.youtube.com/watch?v=_VwpcLiBkAQ", sub: "video" },
      { type: "video", label: "Wireless Networking", url: "https://www.youtube.com/watch?v=YEDutqG4C4U", sub: "video" },
      { type: "video", label: "Network Types", url: "https://www.youtube.com/watch?v=8ExS_LYAe-M", sub: "video" },
      { type: "video", label: "Wireless Encryption", url: "https://www.youtube.com/watch?v=YNcobcHXnnY", sub: "video" },
      { type: "video", label: "Installing Networks", url: "https://www.youtube.com/watch?v=7NLsuBIvVVA", sub: "video" },
      { type: "video", label: "Power", url: "https://www.youtube.com/watch?v=Ok0XpAzwCVQ", sub: "video" },
      { type: "video", label: "Environmental Factors", url: "https://www.youtube.com/watch?v=v7AIXZi7pyA", sub: "video" },
      { type: "video", label: "Network Documentation", url: "https://www.youtube.com/watch?v=CEZyq-fBn3w", sub: "video" },
      { type: "video", label: "Life Cycle Management", url: "https://www.youtube.com/watch?v=E8423-hdsHg", sub: "video" },
      { type: "video", label: "Configuration Management", url: "https://www.youtube.com/watch?v=cbHcjzlLjuc", sub: "video" },
      { type: "video", label: "SNMP", url: "https://www.youtube.com/watch?v=We5MkaEJOs0", sub: "video" },
      { type: "video", label: "Logs and Monitoring", url: "https://www.youtube.com/watch?v=ieqSi5Aicxc", sub: "video" },
      { type: "video", label: "Network Solutions", url: "https://www.youtube.com/watch?v=zIX_SzezCi0", sub: "video" },
      { type: "video", label: "Disaster Recovery", url: "https://www.youtube.com/watch?v=NaXMohP4-vU", sub: "video" },
      { type: "video", label: "Network Redundancy", url: "https://www.youtube.com/watch?v=dsvNPjK0ihM", sub: "video" },
      { type: "video", label: "DHCP", url: "https://www.youtube.com/watch?v=b7fiXM3vO18", sub: "video" },
      { type: "video", label: "Configuring DHCP", url: "https://www.youtube.com/watch?v=Zu70w3YTtpg", sub: "video" },
      { type: "video", label: "IPv6 and SLAAC", url: "https://www.youtube.com/watch?v=A6WVj82by3Y", sub: "video" },
      { type: "video", label: "An Overview of DNS", url: "https://www.youtube.com/watch?v=S4s3vgm4h84", sub: "video" },
      { type: "video", label: "DNS Records", url: "https://www.youtube.com/watch?v=qAyVND44jaE", sub: "video" },
      { type: "video", label: "Time Protocols", url: "https://www.youtube.com/watch?v=9MwHexC3Fkc", sub: "video" },
      { type: "video", label: "VPNs", url: "https://www.youtube.com/watch?v=tm7i0zEitPQ", sub: "video" },
      { type: "video", label: "Remote Access", url: "https://www.youtube.com/watch?v=QbEDRTjcom4", sub: "video" },
      { type: "video", label: "Security Concepts", url: "https://www.youtube.com/watch?v=51W4Fhds7DQ", sub: "video" },
      { type: "video", label: "Authentication", url: "https://www.youtube.com/watch?v=enyRd-8m8SI", sub: "video" },
      { type: "video", label: "Security Technologies", url: "https://www.youtube.com/watch?v=qIQQKCv6P_s", sub: "video" },
      { type: "video", label: "Regulatory Compliance", url: "https://www.youtube.com/watch?v=5KjXu7SvU6E", sub: "video" },
      { type: "video", label: "Segmentation Enforcement", url: "https://www.youtube.com/watch?v=DsOzQLX5cg4", sub: "video" },
      { type: "video", label: "Denial of Service", url: "https://www.youtube.com/watch?v=x8dIr6JYkjA", sub: "video" },
      { type: "video", label: "VLAN Hopping", url: "https://www.youtube.com/watch?v=hcaGiWteVTM", sub: "video" },
      { type: "video", label: "MAC Flooding", url: "https://www.youtube.com/watch?v=ttLNYwt-aq0", sub: "video" },
      { type: "video", label: "ARP and DNS Poisoning", url: "https://www.youtube.com/watch?v=2QijB5GtNE4", sub: "video" },
      { type: "video", label: "Rogue Services", url: "https://www.youtube.com/watch?v=6AcRzyPuOL8", sub: "video" },
      { type: "video", label: "Social Engineering", url: "https://www.youtube.com/watch?v=sF0uBtavItI", sub: "video" },
      { type: "video", label: "Malware", url: "https://www.youtube.com/watch?v=rnfViZdGfmA", sub: "video" },
      { type: "video", label: "Device Security", url: "https://www.youtube.com/watch?v=TZUh1qF6ypI", sub: "video" },
      { type: "video", label: "Security Rules", url: "https://www.youtube.com/watch?v=ORRcLSS9_Ps", sub: "video" },
      { type: "video", label: "Network Troubleshooting Methodology", url: "https://www.youtube.com/watch?v=dovuPm3dGhc", sub: "video" },
      { type: "video", label: "Cable Issues", url: "https://www.youtube.com/watch?v=L6P6ovTEPvU", sub: "video" },
      { type: "video", label: "Interface Issues", url: "https://www.youtube.com/watch?v=7b4RkdITO4Q", sub: "video" },
      { type: "video", label: "Hardware Issues", url: "https://www.youtube.com/watch?v=_IeIUxDe1fo", sub: "video" },
      { type: "video", label: "Switching Issues", url: "https://www.youtube.com/watch?v=rUONzfO11m8", sub: "video" },
      { type: "video", label: "Routing and IP Issues", url: "https://www.youtube.com/watch?v=pbOi48USeVw", sub: "video" },
      { type: "video", label: "Performance Issues", url: "https://www.youtube.com/watch?v=FVxENIjdAJk", sub: "video" },
      { type: "video", label: "Wireless Issues", url: "https://www.youtube.com/watch?v=UO3G_OJhBS4", sub: "video" },
      { type: "video", label: "Software Tools", url: "https://www.youtube.com/watch?v=b81_GeoN12I", sub: "video" },
      { type: "video", label: "Command Line Tools", url: "https://www.youtube.com/watch?v=iYojIK1173k", sub: "video" },
      { type: "video", label: "Hardware Tools", url: "https://www.youtube.com/watch?v=ytcAqNxkI9I", sub: "video" },
      { type: "video", label: "Basic Network Device Commands", url: "https://www.youtube.com/watch?v=3-KakmVmEpo", sub: "video" },
    ],
  },
  {
    id: "security",
    name: "Security+",
    days: [8, 14],
    icon: "🛡️",
    desc: "Prinsip keamanan: threat, vulnerability, cryptography, identity, risk, dan arsitektur keamanan.",
    items: [
      { type: "video", label: "How to Pass Your SY0-701 Security+ Exam", url: "https://www.youtube.com/watch?v=KiEptGbnEBc", sub: "video" },
      { type: "video", label: "Security Goals", url: "https://www.youtube.com/watch?v=STM3EUvL7wg", sub: "video" },
      { type: "video", label: "Security Controls", url: "https://www.youtube.com/watch?v=SBcDGb9l6yo", sub: "video" },
      { type: "video", label: "Security Roles and Responsibilities", url: "https://www.youtube.com/watch?v=XxnCxPEllMg", sub: "video" },
      { type: "video", label: "General Security Concepts", url: "https://www.youtube.com/watch?v=AhaZtj5P2a8", sub: "video" },
      { type: "video", label: "Change Management", url: "https://www.youtube.com/watch?v=cuTVyyS5C7M", sub: "video" },
      { type: "video", label: "Risk Management", url: "https://www.youtube.com/watch?v=zC_Pndpg8-c", sub: "video" },
      { type: "video", label: "Threat Actors", url: "https://www.youtube.com/watch?v=YtT8q2mUM9c", sub: "video" },
      { type: "video", label: "Common Threat Vectors", url: "https://www.youtube.com/watch?v=X_qfMVty4ts", sub: "video" },
      { type: "video", label: "Social Engineering", url: "https://www.youtube.com/watch?v=48wRbMdHFVI", sub: "video" },
      { type: "video", label: "Phishing", url: "https://www.youtube.com/watch?v=H9TYNjcpl-0", sub: "video" },
      { type: "video", label: "Memory Injections", url: "https://www.youtube.com/watch?v=xHAMEF7-inQ", sub: "video" },
      { type: "video", label: "Buffer Overflows", url: "https://www.youtube.com/watch?v=jpsc4c7lntw", sub: "video" },
      { type: "video", label: "Race Conditions", url: "https://www.youtube.com/watch?v=U6BWn81P5Ec", sub: "video" },
      { type: "video", label: "Malicious Code", url: "https://www.youtube.com/watch?v=u61J0xR_XPU", sub: "video" },
      { type: "video", label: "Physical Attacks", url: "https://www.youtube.com/watch?v=LfuTMzZke4g", sub: "video" },
      { type: "video", label: "Adversarial AI", url: "https://www.youtube.com/watch?v=EcGmQjl6XEo", sub: "video" },
      { type: "video", label: "Supply Chain Attacks", url: "https://www.youtube.com/watch?v=-wqU_2ToP1M", sub: "video" },
      { type: "video", label: "Cloud Infrastructure", url: "https://www.youtube.com/watch?v=cLa94BZH_9s", sub: "video" },
      { type: "video", label: "Cloud Security", url: "https://www.youtube.com/watch?v=6xUH0t6ugIM", sub: "video" },
      { type: "video", label: "Network Infrastructure", url: "https://www.youtube.com/watch?v=4lAbGpTDZ18", sub: "video" },
      { type: "video", label: "Application Attacks", url: "https://www.youtube.com/watch?v=9SD6DRCKZFU", sub: "video" },
      { type: "video", label: "Cryptographic Attacks", url: "https://www.youtube.com/watch?v=X3yoNAVuKwA", sub: "video" },
      { type: "video", label: "Password Attacks", url: "https://www.youtube.com/watch?v=z413PV6l_Ys", sub: "video" },
      { type: "video", label: "Indicators of Compromise", url: "https://www.youtube.com/watch?v=akoDmeV3LQo", sub: "video" },
      { type: "video", label: "Segmentation", url: "https://www.youtube.com/watch?v=kBcTczu8FsM", sub: "video" },
      { type: "video", label: "Access Control", url: "https://www.youtube.com/watch?v=0-qeeI5jTqU", sub: "video" },
      { type: "video", label: "Least Privilege", url: "https://www.youtube.com/watch?v=MKptc1lPSw8", sub: "video" },
      { type: "video", label: "Secure Protocols", url: "https://www.youtube.com/watch?v=KbtUrdBy9Yo", sub: "video" },
      { type: "video", label: "Firmware Security", url: "https://www.youtube.com/watch?v=narir8qpGq8", sub: "video" },
      { type: "video", label: "Endpoint Security", url: "https://www.youtube.com/watch?v=qFUOLkEk8AQ", sub: "video" },
      { type: "video", label: "Hardening", url: "https://www.youtube.com/watch?v=PKgw0CLZIhE", sub: "video" },
      { type: "video", label: "Wireless Security", url: "https://www.youtube.com/watch?v=TaTaEvqjjDM", sub: "video" },
      { type: "video", label: "Mobile Device Security", url: "https://www.youtube.com/watch?v=t2JrPrzRDLA", sub: "video" },
      { type: "video", label: "Application Security", url: "https://www.youtube.com/watch?v=V2DCYO-sWRQ", sub: "video" },
      { type: "video", label: "Vulnerability Scanning", url: "https://www.youtube.com/watch?v=WqvCJLpwExY", sub: "video" },
      { type: "video", label: "Cryptography Fundamentals", url: "https://www.youtube.com/watch?v=NBKzlUqzVmE", sub: "video" },
      { type: "video", label: "Symmetric Encryption", url: "https://www.youtube.com/watch?v=DRfAwwdzYpU", sub: "video" },
      { type: "video", label: "Asymmetric Encryption", url: "https://www.youtube.com/watch?v=FDFxGLnZtoY", sub: "video" },
      { type: "video", label: "Hashing", url: "https://www.youtube.com/watch?v=-eZs8wjjGGE", sub: "video" },
      { type: "video", label: "Digital Signatures", url: "https://www.youtube.com/watch?v=Su8ANmAoerU", sub: "video" },
      { type: "video", label: "PKI and Certificates", url: "https://www.youtube.com/watch?v=-VmI3xFJw78", sub: "video" },
      { type: "video", label: "Key Management", url: "https://www.youtube.com/watch?v=nu27ovJ5rqw", sub: "video" },
      { type: "video", label: "Authentication Methods", url: "https://www.youtube.com/watch?v=oIpOuTX2HRs", sub: "video" },
      { type: "video", label: "Authorization Models", url: "https://www.youtube.com/watch?v=Z7OntvK--PQ", sub: "video" },
      { type: "video", label: "Accounting and Auditing", url: "https://www.youtube.com/watch?v=BoxeL5ybOXI", sub: "video" },
      { type: "video", label: "Identity Providers", url: "https://www.youtube.com/watch?v=tSLqrKhUvts", sub: "video" },
      { type: "video", label: "Federation", url: "https://www.youtube.com/watch?v=M_Af6_8JTuo", sub: "video" },
      { type: "video", label: "Access Control Models", url: "https://www.youtube.com/watch?v=ai6qS13gKRo", sub: "video" },
      { type: "video", label: "Physical Security", url: "https://www.youtube.com/watch?v=xDhUBQ_lnUA", sub: "video" },
      { type: "video", label: "Network Security Appliances", url: "https://www.youtube.com/watch?v=yRSqIGjeb7s", sub: "video" },
      { type: "video", label: "Secure Network Design", url: "https://www.youtube.com/watch?v=7aJaEQy6Yoc", sub: "video" },
      { type: "video", label: "Network Security Protocols", url: "https://www.youtube.com/watch?v=-ZfbifHwEVE", sub: "video" },
      { type: "video", label: "Wireless Security Protocols", url: "https://www.youtube.com/watch?v=x72hG9GvkaQ", sub: "video" },
      { type: "video", label: "Application Security Controls", url: "https://www.youtube.com/watch?v=yDeDGCh_PDs", sub: "video" },
      { type: "video", label: "Secure Coding", url: "https://www.youtube.com/watch?v=Fc8ZJfmapbI", sub: "video" },
      { type: "video", label: "Virtualization Security", url: "https://www.youtube.com/watch?v=wXoC46Qr_9Q", sub: "video" },
      { type: "video", label: "Cloud Security Solutions", url: "https://www.youtube.com/watch?v=8qpQ8Q6xxiU", sub: "video" },
      { type: "video", label: "Infrastructure as Code", url: "https://www.youtube.com/watch?v=jd001Hj7XWM", sub: "video" },
      { type: "video", label: "Incident Response", url: "https://www.youtube.com/watch?v=HDiNPPrGhzE", sub: "video" },
      { type: "video", label: "Digital Forensics", url: "https://www.youtube.com/watch?v=Ap3Z_0ZdqpQ", sub: "video" },
      { type: "video", label: "Disaster Recovery", url: "https://www.youtube.com/watch?v=l64La1xYXL4", sub: "video" },
      { type: "video", label: "Business Continuity", url: "https://www.youtube.com/watch?v=7QuYupuic3Q", sub: "video" },
      { type: "video", label: "Risk Management Frameworks", url: "https://www.youtube.com/watch?v=WlOslEy3ztg", sub: "video" },
      { type: "video", label: "Security Policies", url: "https://www.youtube.com/watch?v=QhLQ6J4satw", sub: "video" },
      { type: "video", label: "Security Standards", url: "https://www.youtube.com/watch?v=mq1HRM-zGtQ", sub: "video" },
      { type: "video", label: "Security Procedures", url: "https://www.youtube.com/watch?v=uU3e_ntg-3g", sub: "video" },
      { type: "video", label: "Governance", url: "https://www.youtube.com/watch?v=R0W0_gZCVzk", sub: "video" },
      { type: "video", label: "Compliance", url: "https://www.youtube.com/watch?v=71RQaYQ4QSw", sub: "video" },
      { type: "video", label: "Risk Assessment", url: "https://www.youtube.com/watch?v=leX_Qa7wqB4", sub: "video" },
      { type: "video", label: "Third-Party Risk", url: "https://www.youtube.com/watch?v=sb0dRaQbuBA", sub: "video" },
      { type: "video", label: "Data Protection", url: "https://www.youtube.com/watch?v=WGlT6-gNwqY", sub: "video" },
      { type: "video", label: "Data Classification", url: "https://www.youtube.com/watch?v=IhT7Odu4xHc", sub: "video" },
      { type: "video", label: "Data States", url: "https://www.youtube.com/watch?v=8mGSwRScqIM", sub: "video" },
      { type: "video", label: "Data Sovereignty", url: "https://www.youtube.com/watch?v=-EY45MimSBM", sub: "video" },
      { type: "video", label: "Log Management", url: "https://www.youtube.com/watch?v=BWPJD9Eb9iE", sub: "video" },
      { type: "video", label: "SIEM", url: "https://www.youtube.com/watch?v=YQKbs0ug0XQ", sub: "video" },
      { type: "video", label: "SOAR", url: "https://www.youtube.com/watch?v=iAR6SgvtezY", sub: "video" },
      { type: "video", label: "Threat Intelligence", url: "https://www.youtube.com/watch?v=KaqKoKNEKnE", sub: "video" },
      { type: "video", label: "Vulnerability Management", url: "https://www.youtube.com/watch?v=fFvXy3WkLpA", sub: "video" },
      { type: "video", label: "Penetration Testing", url: "https://www.youtube.com/watch?v=BJ2UMB4a04g", sub: "video" },
      { type: "video", label: "Security Automation", url: "https://www.youtube.com/watch?v=9B0mtWk_AM0", sub: "video" },
      { type: "video", label: "PKI Management", url: "https://www.youtube.com/watch?v=86fruE9jkKk", sub: "video" },
      { type: "video", label: "Certificate Management", url: "https://www.youtube.com/watch?v=-LevHAzXgFs", sub: "video" },
      { type: "video", label: "Cryptographic Concepts", url: "https://www.youtube.com/watch?v=eyVy1gKCuAU", sub: "video" },
      { type: "video", label: "Digital Certificates", url: "https://www.youtube.com/watch?v=P9xakfmX70c", sub: "video" },
      { type: "video", label: "Secure Communications", url: "https://www.youtube.com/watch?v=np2WI_rM-Ok", sub: "video" },
      { type: "video", label: "Network Attacks", url: "https://www.youtube.com/watch?v=nNiNTviiacU", sub: "video" },
      { type: "video", label: "Application Attacks", url: "https://www.youtube.com/watch?v=VgNyh4HEqSU", sub: "video" },
      { type: "video", label: "Cryptographic Attacks", url: "https://www.youtube.com/watch?v=I_c0D49uCwQ", sub: "video" },
      { type: "video", label: "Password Attacks", url: "https://www.youtube.com/watch?v=4dpTyRM6BU8", sub: "video" },
      { type: "video", label: "Physical Attacks", url: "https://www.youtube.com/watch?v=9NAKCyOtFH0", sub: "video" },
      { type: "video", label: "Social Engineering Attacks", url: "https://www.youtube.com/watch?v=v6ht9efsnRI", sub: "video" },
      { type: "video", label: "Web Attacks", url: "https://www.youtube.com/watch?v=ZDJ-BLPLWq4", sub: "video" },
      { type: "video", label: "Cloud Attacks", url: "https://www.youtube.com/watch?v=83pCkSSj1IQ", sub: "video" },
      { type: "video", label: "Mobile Attacks", url: "https://www.youtube.com/watch?v=ZoOyyqhptik", sub: "video" },
      { type: "video", label: "IoT Attacks", url: "https://www.youtube.com/watch?v=9ANHcZwJfdQ", sub: "video" },
      { type: "video", label: "AI Attacks", url: "https://www.youtube.com/watch?v=MpIzA4fNWew", sub: "video" },
      { type: "video", label: "Supply Chain Attacks", url: "https://www.youtube.com/watch?v=eMOe-PLBy1k", sub: "video" },
      { type: "video", label: "Risk Management", url: "https://www.youtube.com/watch?v=R9ojg881dLs", sub: "video" },
      { type: "video", label: "Business Impact Analysis", url: "https://www.youtube.com/watch?v=X2UiMLxRdhE", sub: "video" },
      { type: "video", label: "Incident Response Planning", url: "https://www.youtube.com/watch?v=CYFe16lCRMk", sub: "video" },
      { type: "video", label: "Disaster Recovery Planning", url: "https://www.youtube.com/watch?v=UtDWApdO8Zk", sub: "video" },
      { type: "video", label: "Business Continuity Planning", url: "https://www.youtube.com/watch?v=EDru1LTYDJw", sub: "video" },
      { type: "video", label: "Tabletop Exercises", url: "https://www.youtube.com/watch?v=5kY9kvzeWjA", sub: "video" },
      { type: "video", label: "Security Awareness", url: "https://www.youtube.com/watch?v=jBvdRpXaomk", sub: "video" },
      { type: "video", label: "Security Training", url: "https://www.youtube.com/watch?v=vJINnOZyQNg", sub: "video" },
      { type: "video", label: "User Behavior Analytics", url: "https://www.youtube.com/watch?v=4tGFraaP48Q", sub: "video" },
      { type: "video", label: "Identity and Access Management", url: "https://www.youtube.com/watch?v=gxNi-04yP8Q", sub: "video" },
      { type: "video", label: "Privileged Access Management", url: "https://www.youtube.com/watch?v=cLhUMoQS1a8", sub: "video" },
      { type: "video", label: "Zero Trust Architecture", url: "https://www.youtube.com/watch?v=Ykx7t54y-oo", sub: "video" },
      { type: "video", label: "Microsegmentation", url: "https://www.youtube.com/watch?v=pmyuWY7Pbag", sub: "video" },
      { type: "video", label: "Secure Access Service Edge", url: "https://www.youtube.com/watch?v=myI-v3mj7Kc", sub: "video" },
      { type: "video", label: "Software Defined Networking", url: "https://www.youtube.com/watch?v=13KNjPexnEI", sub: "video" },
      { type: "video", label: "Cloud Access Security Broker", url: "https://www.youtube.com/watch?v=HSZxjj1YAh8", sub: "video" },
      { type: "video", label: "Network Access Control", url: "https://www.youtube.com/watch?v=IjJf4jLtONQ", sub: "video" },
      { type: "video", label: "Virtual Private Networks", url: "https://www.youtube.com/watch?v=WGXrbAh0LUI", sub: "video" },
      { type: "video", label: "Secure Sockets Layer", url: "https://www.youtube.com/watch?v=uo2Yw720mv4", sub: "video" },
      { type: "video", label: "Transport Layer Security", url: "https://www.youtube.com/watch?v=wEMzVfwBiWY", sub: "video" },
      { type: "video", label: "Internet Protocol Security", url: "https://www.youtube.com/watch?v=W_Npxwk4fbI", sub: "video" },
      { type: "video", label: "Secure Shell", url: "https://www.youtube.com/watch?v=WQRZMMLUkGE", sub: "video" },
    ],
  },
  {
    id: "linux",
    name: "Linux",
    days: [15, 28],
    icon: "🐧",
    desc: "Sistem operasi Linux: command line, filesystem, permissions, shell scripting, dan administrasi dasar.",
    items: [
      { type: "resource", label: "Linux Journey", url: "https://linuxjourney.com/", sub: "tutorial" },
      { type: "resource", label: "Linux Unhatched (Cisco NetAcad)", url: "https://www.netacad.com/courses/linux-unhatched", sub: "course" },
      { type: "resource", label: "LabEx — Linux Hands-on Labs", url: "https://labex.io/free-labs/linux", sub: "labs" },
      { type: "task", label: "Pelajari command line dasar (ls, cd, pwd, mkdir, rm, cp, mv)", url: null, sub: "task" },
      { type: "task", label: "Pahami struktur filesystem Linux (/, /etc, /var, /home)", url: null, sub: "task" },
      { type: "task", label: "Pelajari permissions & ownership (chmod, chown, umask)", url: null, sub: "task" },
      { type: "task", label: "Pelajari proses & manajemen job (ps, top, kill, &)", url: null, sub: "task" },
      { type: "task", label: "Pelajari redirection & pipes (>, >>, |)", url: null, sub: "task" },
      { type: "task", label: "Pelajari text processing (grep, sed, awk, sort, uniq)", url: null, sub: "task" },
      { type: "task", label: "Pelajari package management (apt/dnf)", url: null, sub: "task" },
      { type: "task", label: "Pelajari networking dasar (ip, ss, ping, curl)", url: null, sub: "task" },
      { type: "task", label: "Pelajari user & group management", url: null, sub: "task" },
      { type: "task", label: "Pelajari cron jobs & scheduling", url: null, sub: "task" },
      { type: "task", label: "Pelajari shell scripting dasar", url: null, sub: "task" },
      { type: "task", label: "Selesaikan Linux Unhatched (Cisco NetAcad)", url: null, sub: "task" },
      { type: "task", label: "Selesaikan lab Linux di LabEx", url: null, sub: "task" },
      { type: "task", label: "Praktik: buat script backup otomatis sederhana", url: null, sub: "task" },
    ],
  },
  {
    id: "python",
    name: "Python",
    days: [29, 42],
    icon: "🐍",
    desc: "Pemrograman Python untuk keamanan: sintaks, struktur data, scripting, dan otomasi.",
    items: [
      { type: "resource", label: "freeCodeCamp — Learn Python (Full Course)", url: "https://www.youtube.com/watch?v=rfscVS0vtbw", sub: "video" },
      { type: "resource", label: "Codecademy — Learn Python", url: "https://codecademy.com/learn/learn-python", sub: "course" },
      { type: "resource", label: "SoloLearn — Python Tutorial", url: "https://sololearn.com/Course/Python/", sub: "tutorial" },
      { type: "resource", label: "Real Python", url: "https://realpython.com/", sub: "reference" },
      { type: "resource", label: "HackerRank — Python", url: "https://www.hackerrank.com/domains/python", sub: "practice" },
      { type: "resource", label: "LabEx — Python by Labs", url: "https://labex.io/free-labs/python", sub: "labs" },
      { type: "resource", label: "TheCyberMentor — Python for Cybersecurity", url: "https://www.youtube.com/watch?v=egg-GoT5iVk", sub: "video" },
      { type: "task", label: "Pelajari variabel, tipe data, dan operator", url: null, sub: "task" },
      { type: "task", label: "Pelajari kontrol alur (if/else, loop)", url: null, sub: "task" },
      { type: "task", label: "Pelajari fungsi & scope", url: null, sub: "task" },
      { type: "task", label: "Pelajari list, tuple, dict, set", url: null, sub: "task" },
      { type: "task", label: "Pelajari string manipulation", url: null, sub: "task" },
      { type: "task", label: "Pelajari file I/O (baca/tulis file)", url: null, sub: "task" },
      { type: "task", label: "Pelajari exception handling (try/except)", url: null, sub: "task" },
      { type: "task", label: "Pelajari modul & packages", url: null, sub: "task" },
      { type: "task", label: "Pelajari regular expression (re)", url: null, sub: "task" },
      { type: "task", label: "Pelajari networking dengan socket", url: null, sub: "task" },
      { type: "task", label: "Pelajari HTTP requests (requests library)", url: null, sub: "task" },
      { type: "task", label: "Selesaikan Python track Codecademy (free tier)", url: null, sub: "task" },
      { type: "task", label: "Kerjakan soal Python di HackerRank", url: null, sub: "task" },
      { type: "task", label: "Praktik: buat port scanner sederhana (lab legal)", url: null, sub: "task" },
    ],
  },
  {
    id: "traffic",
    name: "Traffic Analysis",
    days: [43, 56],
    icon: "📡",
    desc: "Analisis lalu lintas jaringan: Wireshark, tcpdump, Suricata IDS/IPS, dan packet inspection.",
    items: [
      { type: "resource", label: "Wireshark University", url: "https://www.wireshark.org/#educationalContent", sub: "course" },
      { type: "resource", label: "Wireshark Tutorial (Guru99)", url: "https://guru99.com/wireshark-tutorial.html", sub: "tutorial" },
      { type: "resource", label: "TCPdump Tutorial (Daniel Miessler)", url: "https://danielmiessler.com/study/tcpdump/", sub: "tutorial" },
      { type: "resource", label: "Suricata Quickstart Guide", url: "https://docs.suricata.io/en/latest/quickstart.html", sub: "docs" },
      { type: "resource", label: "Wireshark Tutorial for Beginners (YouTube)", url: "https://www.youtube.com/watch?v=NjvR4LmwcMU&list=PLBf0hzazHTGPgyxeEj_9LBHiqjtNEjsgt", sub: "video" },
      { type: "resource", label: "Suricata Network IDS/IPS (YouTube)", url: "https://www.youtube.com/watch?v=S0-vsjhPDN0", sub: "video" },
      { type: "task", label: "Pelajari cara menangkap packet dengan Wireshark", url: null, sub: "task" },
      { type: "task", label: "Pahami display filter & capture filter", url: null, sub: "task" },
      { type: "task", label: "Analisis handshake TCP (SYN, SYN-ACK, ACK)", url: null, sub: "task" },
      { type: "task", label: "Analisis HTTP/DNS traffic", url: null, sub: "task" },
      { type: "task", label: "Pelajari tcpdump command line", url: null, sub: "task" },
      { type: "task", label: "Pelajari dasar Suricata rules", url: null, sub: "task" },
      { type: "task", label: "Deteksi pola mencurigakan di traffic", url: null, sub: "task" },
      { type: "task", label: "Praktik: analisis file .pcap sample", url: null, sub: "task" },
    ],
  },
  {
    id: "git",
    name: "Git",
    days: [57, 63],
    icon: "🔀",
    desc: "Version control dengan Git: commit, branch, merge, rebase, dan workflow kolaborasi.",
    items: [
      { type: "resource", label: "Codecademy — Git for Beginners", url: "https://codecademy.com/learn/learn-git", sub: "course" },
      { type: "resource", label: "Git Immersion", url: "http://gitimmersion.com", sub: "tutorial" },
      { type: "resource", label: "Try Git", url: "https://try.github.io", sub: "interactive" },
      { type: "resource", label: "Learn Git Branching", url: "https://learngitbranching.js.org/", sub: "interactive" },
      { type: "task", label: "Pelajari git init, add, commit, status, log", url: null, sub: "task" },
      { type: "task", label: "Pelajari branch, checkout, merge", url: null, sub: "task" },
      { type: "task", label: "Pelajari remote (push, pull, fetch)", url: null, sub: "task" },
      { type: "task", label: "Pelajari rebase & conflict resolution", url: null, sub: "task" },
      { type: "task", label: "Pelajari .gitignore & best practices", url: null, sub: "task" },
      { type: "task", label: "Selesaikan Learn Git Branching", url: null, sub: "task" },
      { type: "task", label: "Praktik: kelola repo project sendiri di GitHub", url: null, sub: "task" },
    ],
  },
  {
    id: "elk",
    name: "ELK Stack",
    days: [64, 70],
    icon: "📊",
    desc: "SIEM & log analysis dengan Elasticsearch, Logstash, Kibana.",
    items: [
      { type: "resource", label: "Complete Guide to ELK Stack (Logz.io)", url: "https://logz.io/learn/complete-guide-elk-stack/", sub: "tutorial" },
      { type: "resource", label: "Elastic Stack Getting Started", url: "https://www.elastic.co/docs/get-started", sub: "docs" },
      { type: "task", label: "Pahami konsep SIEM & log management", url: null, sub: "task" },
      { type: "task", label: "Pelajari Elasticsearch (index, query)", url: null, sub: "task" },
      { type: "task", label: "Pelajari Logstash (ingest & pipeline)", url: null, sub: "task" },
      { type: "task", label: "Pelajari Kibana (visualisasi & dashboard)", url: null, sub: "task" },
      { type: "task", label: "Praktik: ingest sample logs & buat dashboard", url: null, sub: "task" },
    ],
  },
  {
    id: "cloud",
    name: "Cloud Platforms",
    days: [71, 77],
    icon: "☁️",
    desc: "Keamanan cloud: pilih salah satu antara GCP, AWS, atau Azure.",
    items: [
      { type: "resource", label: "AWS Getting Started", url: "https://aws.amazon.com/getting-started/", sub: "tutorial" },
      { type: "resource", label: "AWS Tutorials", url: "https://aws.amazon.com/tutorials/", sub: "tutorial" },
      { type: "resource", label: "AWS Cloud Quest", url: "https://aws.amazon.com/training/digital/aws-cloud-quest/", sub: "interactive" },
      { type: "resource", label: "Azure Fundamentals (Microsoft Learn)", url: "https://learn.microsoft.com/en-us/training/azure/", sub: "course" },
      { type: "resource", label: "GCP Getting Started", url: "https://cloud.google.com/getting-started/", sub: "tutorial" },
      { type: "resource", label: "Google Cloud Skills Boost", url: "https://www.cloudskillsboost.google", sub: "labs" },
      { type: "task", label: "Pilih satu cloud provider (AWS/Azure/GCP)", url: null, sub: "task" },
      { type: "task", label: "Pelajari konsep IAM & least privilege", url: null, sub: "task" },
      { type: "task", label: "Pelajari virtual network / VPC", url: null, sub: "task" },
      { type: "task", label: "Pelajari storage & compute services", url: null, sub: "task" },
      { type: "task", label: "Pelajari cloud security best practices", url: null, sub: "task" },
      { type: "task", label: "Praktik: deploy resource di free tier", url: null, sub: "task" },
    ],
  },
  {
    id: "review",
    name: "Review & Practice",
    days: [78, 84],
    icon: "🔁",
    desc: "Ulangi materi lemah, kerjakan lab TryHackMe, dan bangun home lab.",
    items: [
      { type: "resource", label: "TryHackMe", url: "https://tryhackme.com", sub: "labs" },
      { type: "resource", label: "VirtualBox", url: "https://www.virtualbox.org/", sub: "tool" },
      { type: "resource", label: "VMware Workstation Player", url: "https://www.vmware.com/products/workstation-player.html", sub: "tool" },
      { type: "task", label: "Review materi Day 1-77 yang masih lemah", url: null, sub: "task" },
      { type: "task", label: "Selesaikan challenge di TryHackMe", url: null, sub: "task" },
      { type: "task", label: "Setup home lab (VirtualBox/VMware)", url: null, sub: "task" },
      { type: "task", label: "Bangun project kecil gabungan networking+Linux+Python+security", url: null, sub: "task" },
    ],
  },
  {
    id: "hacking",
    name: "Hacking",
    days: [85, 90],
    icon: "🎯",
    desc: "Penetration testing & ethical hacking: Hack The Box, Vulnhub, dan video TheCyberMentor.",
    items: [
      { type: "resource", label: "Hack The Box", url: "https://hackthebox.com", sub: "labs" },
      { type: "resource", label: "Vulnhub", url: "https://vulnhub.com", sub: "labs" },
      { type: "resource", label: "Cyber Talents", url: "https://cybertalents.com", sub: "labs" },
      { type: "resource", label: "TheCyberMentor — Ethical Hacking Part 1", url: "https://www.youtube.com/watch?v=3FNYvj2U0HM", sub: "video" },
      { type: "resource", label: "TheCyberMentor — Ethical Hacking Part 2", url: "https://www.youtube.com/watch?v=sH4JCwjybGs", sub: "video" },
      { type: "task", label: "Pelajari methodology penetration testing", url: null, sub: "task" },
      { type: "task", label: "Pelajari reconnaissance & enumeration", url: null, sub: "task" },
      { type: "task", label: "Kerjakan mesin vulnerable di HTB/Vulnhub", url: null, sub: "task" },
      { type: "task", label: "Tonton Ethical Hacking Part 1 & 2", url: null, sub: "task" },
      { type: "task", label: "Praktik di lab legal saja (HTB/Vulnhub/TryHackMe)", url: null, sub: "task" },
    ],
  },
  {
    id: "career",
    name: "Career",
    days: [91, 95],
    icon: "💼",
    desc: "Landing the job: resume satu halaman dan cara melamar.",
    items: [
      { type: "resource", label: "Killer Cyber Resume (BowTiedCyber)", url: "https://bowtiedcyber.substack.com/p/killer-cyber-resume-part-ii", sub: "guide" },
      { type: "resource", label: "Indeed", url: "https://indeed.com", sub: "jobs" },
      { type: "resource", label: "LinkedIn", url: "https://linkedin.com", sub: "jobs" },
      { type: "resource", label: "CyberSeek Career Pathways", url: "https://www.cyberseek.org/pathway.html", sub: "reference" },
      { type: "task", label: "Buat resume satu halaman (simpan juga sebagai cv.md)", url: null, sub: "task" },
      { type: "task", label: "Daftarkan pengalaman lab/CTF/project ke resume", url: null, sub: "task" },
      { type: "task", label: "Riset career pathway di CyberSeek", url: null, sub: "task" },
      { type: "task", label: "Siapkan profil LinkedIn", url: null, sub: "task" },
    ],
  },
];

export const MATH_TRACK: Phase = {
  id: "mathematics",
  name: "Mathematics",
  icon: "🧠",
  desc: "Seluruh matematika dari dasar hingga lanjut — 193 video unik (dedup), berurutan.",
  url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9FoGQeUMFZ4SWZsr30jlUYK",
  items: [
    { type: 'video', label: "Introduction to Mathematics", url: "https://www.youtube.com/watch?v=JbhBdOfMEPs", sub: 'video' },
    { type: 'video', label: "Addition and Subtraction of Small Numbers", url: "https://www.youtube.com/watch?v=rV7WjNWHOsI", sub: 'video' },
    { type: 'video', label: "Multiplication and Division of Small Numbers", url: "https://www.youtube.com/watch?v=fr04p6Ar9ic", sub: 'video' },
    { type: 'video', label: "Understanding Fractions, Improper Fractions, and Mixed Numbers", url: "https://www.youtube.com/watch?v=qyW2mWvvtZ8", sub: 'video' },
    { type: 'video', label: "Large Whole Numbers: Place Values and Estimating", url: "https://www.youtube.com/watch?v=AkWtUOwlUgs", sub: 'video' },
    { type: 'video', label: "Decimals: Notation and Operations", url: "https://www.youtube.com/watch?v=jC4SWFag6Qw", sub: 'video' },
    { type: 'video', label: "Working With Percentages", url: "https://www.youtube.com/watch?v=n9fgcm0Pwgs", sub: 'video' },
    { type: 'video', label: "Converting Between Fractions, Decimals, and Percentages", url: "https://www.youtube.com/watch?v=-Xt4UDk7Kzw", sub: 'video' },
    { type: 'video', label: "Addition and Subtraction of Large Numbers", url: "https://www.youtube.com/watch?v=YFyOsvnr9ig", sub: 'video' },
    { type: 'video', label: "The Distributive Property for Arithmetic", url: "https://www.youtube.com/watch?v=LC_R2Zh66fU", sub: 'video' },
    { type: 'video', label: "Multiplication of Large Numbers", url: "https://www.youtube.com/watch?v=s1Ly3cX4yHc", sub: 'video' },
    { type: 'video', label: "Division of Large Numbers: Long Division", url: "https://www.youtube.com/watch?v=rI2peJT2Ty8", sub: 'video' },
    { type: 'video', label: "Negative Numbers", url: "https://www.youtube.com/watch?v=3-5DKCLJspM", sub: 'video' },
    { type: 'video', label: "Understanding Exponents and Their Operations", url: "https://www.youtube.com/watch?v=K_TD9GuP9uQ", sub: 'video' },
    { type: 'video', label: "Order of Arithmetic Operations: PEMDAS", url: "https://www.youtube.com/watch?v=y_f7c3ztFrI", sub: 'video' },
    { type: 'video', label: "Divisibility, Prime Numbers, and Prime Factorization", url: "https://www.youtube.com/watch?v=WZWKJG9fxnU", sub: 'video' },
    { type: 'video', label: "Least Common Multiple (LCM)", url: "https://www.youtube.com/watch?v=sae1IoToQ0M", sub: 'video' },
    { type: 'video', label: "Greatest Common Factor (GCF)", url: "https://www.youtube.com/watch?v=GFmdqe4z9zU", sub: 'video' },
    { type: 'video', label: "Addition and Subtraction of Fractions", url: "https://www.youtube.com/watch?v=-ijpdtjDNZw", sub: 'video' },
    { type: 'video', label: "Multiplication and Division of Fractions", url: "https://www.youtube.com/watch?v=Q9MCRjrrd6E", sub: 'video' },
    { type: 'video', label: "Analyzing Sets of Data: Range, Mean, Median, and Mode", url: "https://www.youtube.com/watch?v=FM7Q2yVLZIc", sub: 'video' },
    { type: 'video', label: "Introduction to Algebra: Using Variables", url: "https://www.youtube.com/watch?v=WZdZhuUSmpM", sub: 'video' },
    { type: 'video', label: "Basic Number Properties for Algebra", url: "https://www.youtube.com/watch?v=0bZ2GcCTtCA", sub: 'video' },
    { type: 'video', label: "Algebraic Equations and Their Solutions", url: "https://www.youtube.com/watch?v=2mnQ3t02Tss", sub: 'video' },
    { type: 'video', label: "Algebraic Equations With Variables on Both Sides", url: "https://www.youtube.com/watch?v=aJ0abU348ds", sub: 'video' },
    { type: 'video', label: "Algebraic Word Problems", url: "https://www.youtube.com/watch?v=jOJLfQq9ktw", sub: 'video' },
    { type: 'video', label: "Solving Algebraic Inequalities", url: "https://www.youtube.com/watch?v=uBxs7cSgOes", sub: 'video' },
    { type: 'video', label: "Square Roots, Cube Roots, and Other Roots", url: "https://www.youtube.com/watch?v=7vomY6g-f3Q", sub: 'video' },
    { type: 'video', label: "Simplifying Expressions With Roots and Exponents", url: "https://www.youtube.com/watch?v=OAIctPYiMrw", sub: 'video' },
    { type: 'video', label: "Solving Algebraic Equations With Roots and Exponents", url: "https://www.youtube.com/watch?v=EnJuHTq0ni0", sub: 'video' },
    { type: 'video', label: "Introduction to Polynomials", url: "https://www.youtube.com/watch?v=nPPNgin7W7Y", sub: 'video' },
    { type: 'video', label: "Adding and Subtracting Polynomials", url: "https://www.youtube.com/watch?v=0aJBtUOXpsk", sub: 'video' },
    { type: 'video', label: "Multiplying Binomials by the FOIL Method", url: "https://www.youtube.com/watch?v=RTC7RIwdZcE", sub: 'video' },
    { type: 'video', label: "Solving Quadratics by Factoring", url: "https://www.youtube.com/watch?v=GuwofNeT9ok", sub: 'video' },
    { type: 'video', label: "Solving Quadratics by Completing the Square", url: "https://www.youtube.com/watch?v=P8W2M0jq2Qs", sub: 'video' },
    { type: 'video', label: "Solving Quadratics by Using the Quadratic Formula", url: "https://www.youtube.com/watch?v=UTuxHsaH-gQ", sub: 'video' },
    { type: 'video', label: "Solving Higher-Degree Polynomials by Synthetic Division and the Rational Roots Test", url: "https://www.youtube.com/watch?v=WRkgMDVIETE", sub: 'video' },
    { type: 'video', label: "Manipulating Rational Expressions: Simplification and Operations", url: "https://www.youtube.com/watch?v=KfrkcGx2Xl8", sub: 'video' },
    { type: 'video', label: "Graphing in Algebra: Ordered Pairs and the Coordinate Plane", url: "https://www.youtube.com/watch?v=ntzgiu7Ta0s", sub: 'video' },
    { type: 'video', label: "Graphing Lines in Algebra: Understanding Slopes and Y-Intercepts", url: "https://www.youtube.com/watch?v=lz8zVJxRFX8", sub: 'video' },
    { type: 'video', label: "Graphing Lines in Slope-Intercept Form (y = mx + b)", url: "https://www.youtube.com/watch?v=T-acWVybQtk", sub: 'video' },
    { type: 'video', label: "Graphing Lines in Standard Form (ax + by = c)", url: "https://www.youtube.com/watch?v=-DnmoFnQUtk", sub: 'video' },
    { type: 'video', label: "Graphing Parallel and Perpendicular Lines", url: "https://www.youtube.com/watch?v=0oe-GqFrYFU", sub: 'video' },
    { type: 'video', label: "Solving Systems of Two Equations and Two Unknowns: Graphing, Substitution, and Elimination", url: "https://www.youtube.com/watch?v=2DzmE3_QS-E", sub: 'video' },
    { type: 'video', label: "Absolute Values: Defining, Calculating, and Graphing", url: "https://www.youtube.com/watch?v=Wirk4o3FHPA", sub: 'video' },
    { type: 'video', label: "What are the Types of Numbers? Real vs. Imaginary, Rational vs. Irrational", url: "https://www.youtube.com/watch?v=QUGmwPwtbpg", sub: 'video' },
    { type: 'video', label: "Introduction to Geometry: Ancient Greece and the Pythagoreans", url: "https://www.youtube.com/watch?v=THtc8pDU7J8", sub: 'video' },
    { type: 'video', label: "Basic Euclidean Geometry: Points, Lines, and Planes", url: "https://www.youtube.com/watch?v=JHMB_ob89qs", sub: 'video' },
    { type: 'video', label: "Types of Angles and Angle Relationships", url: "https://www.youtube.com/watch?v=dA94zyaLuhk", sub: 'video' },
    { type: 'video', label: "Types of Triangles in Euclidean Geometry", url: "https://www.youtube.com/watch?v=lQ5AuNVjxhI", sub: 'video' },
    { type: 'video', label: "Proving Triangle Congruence and Similarity", url: "https://www.youtube.com/watch?v=mJ4Ms6SXEgg", sub: 'video' },
    { type: 'video', label: "Special Lines in Triangles: Bisectors, Medians, and Altitudes", url: "https://www.youtube.com/watch?v=ByWrUSKHTGc", sub: 'video' },
    { type: 'video', label: "The Triangle Midsegment Theorem", url: "https://www.youtube.com/watch?v=ojMemmYifxM", sub: 'video' },
    { type: 'video', label: "The Pythagorean Theorem", url: "https://www.youtube.com/watch?v=37PX8DV_b9Y", sub: 'video' },
    { type: 'video', label: "Types of Quadrilaterals and Other Polygons", url: "https://www.youtube.com/watch?v=jTZs8bRoWxE", sub: 'video' },
    { type: 'video', label: "Calculating the Perimeter of Polygons", url: "https://www.youtube.com/watch?v=J11IU3C86Yc", sub: 'video' },
    { type: 'video', label: "Circles: Radius, Diameter, Chords, Circumference, and Sectors", url: "https://www.youtube.com/watch?v=SBIv5-7RbQY", sub: 'video' },
    { type: 'video', label: "Calculating the Area of Shapes", url: "https://www.youtube.com/watch?v=_zzV2DV19IU", sub: 'video' },
    { type: 'video', label: "Proving the Pythagorean Theorem", url: "https://www.youtube.com/watch?v=VjI4LtotC2o", sub: 'video' },
    { type: 'video', label: "Three-Dimensional Shapes Part 1: Types, Calculating Surface Area", url: "https://www.youtube.com/watch?v=sAd3Eo25Bbg", sub: 'video' },
    { type: 'video', label: "Three-Dimensional Shapes Part 2: Calculating Volume", url: "https://www.youtube.com/watch?v=CI-G9_bTKuw", sub: 'video' },
    { type: 'video', label: "Back to Algebra: What are Functions?", url: "https://www.youtube.com/watch?v=LmudKHXSMp4", sub: 'video' },
    { type: 'video', label: "Manipulating Functions Algebraically and Evaluating Composite Functions", url: "https://www.youtube.com/watch?v=q3zmcFvHxP4", sub: 'video' },
    { type: 'video', label: "Graphing Algebraic Functions: Domain and Range, Maxima and Minima", url: "https://www.youtube.com/watch?v=EjsQWKq-dGQ", sub: 'video' },
    { type: 'video', label: "Transforming Algebraic Functions: Shifting, Stretching, and Reflecting", url: "https://www.youtube.com/watch?v=MkP1LJR2PyM", sub: 'video' },
    { type: 'video', label: "Continuous, Discontinuous, and Piecewise Functions", url: "https://www.youtube.com/watch?v=BIQrnx-vvx8", sub: 'video' },
    { type: 'video', label: "Inverse Functions", url: "https://www.youtube.com/watch?v=9fJsrnE1go0", sub: 'video' },
    { type: 'video', label: "The Distance Formula: Finding the Distance Between Two Points", url: "https://www.youtube.com/watch?v=wzQstigxbuo", sub: 'video' },
    { type: 'video', label: "Graphing Conic Sections Part 1: Circles", url: "https://www.youtube.com/watch?v=JUvo3GrgWHk", sub: 'video' },
    { type: 'video', label: "Graphing Conic Sections Part 2: Ellipses", url: "https://www.youtube.com/watch?v=iwRlllkqADw", sub: 'video' },
    { type: 'video', label: "Graphing Conic Sections Part 3: Parabolas in Standard Form", url: "https://www.youtube.com/watch?v=hvJkCMzFiX8", sub: 'video' },
    { type: 'video', label: "Graphing Conic Sections Part 4: Hyperbolas", url: "https://www.youtube.com/watch?v=h5aVROOmI-Q", sub: 'video' },
    { type: 'video', label: "Graphing Higher-Degree Polynomials: The Leading Coefficient Test and Finding Zeros", url: "https://www.youtube.com/watch?v=CHEtGgTexHI", sub: 'video' },
    { type: 'video', label: "Graphing Rational Functions and Their Asymptotes", url: "https://www.youtube.com/watch?v=fy45qX8cUwQ", sub: 'video' },
    { type: 'video', label: "Solving and Graphing Polynomial and Rational Inequalities", url: "https://www.youtube.com/watch?v=Es37gGo5F4Y", sub: 'video' },
    { type: 'video', label: "Evaluating and Graphing Exponential Functions", url: "https://www.youtube.com/watch?v=tAaDItpC8OI", sub: 'video' },
    { type: 'video', label: "Logarithms Part 1: Evaluation of Logs and Graphing Logarithmic Functions", url: "https://www.youtube.com/watch?v=1Yv4fEsGpvM", sub: 'video' },
    { type: 'video', label: "Logarithms Part 2: Base Ten Logs, Natural Logs, and the Change-Of-Base Property", url: "https://www.youtube.com/watch?v=sQ2ix7QcGwQ", sub: 'video' },
    { type: 'video', label: "Logarithms Part 3: Properties of Logs, Expanding Logarithmic Expressions", url: "https://www.youtube.com/watch?v=MSTSBW8LPRM", sub: 'video' },
    { type: 'video', label: "Solving Exponential and Logarithmic Equations", url: "https://www.youtube.com/watch?v=10I_TVuYLkQ", sub: 'video' },
    { type: 'video', label: "Complex Numbers: Operations, Complex Conjugates, and the Linear Factorization Theorem", url: "https://www.youtube.com/watch?v=Yddjxj49C_M", sub: 'video' },
    { type: 'video', label: "Set Theory: Types of Sets, Unions and Intersections", url: "https://www.youtube.com/watch?v=6JkCmZAQaio", sub: 'video' },
    { type: 'video', label: "Sequences, Factorials, and Summation Notation", url: "https://www.youtube.com/watch?v=-DPkqpmm1sI", sub: 'video' },
    { type: 'video', label: "Theoretical Probability, Permutations and Combinations", url: "https://www.youtube.com/watch?v=0ZsSRx0o0zE", sub: 'video' },
    { type: 'video', label: "Introduction to Trigonometry: Angles and Radians", url: "https://www.youtube.com/watch?v=0GkmnPdD6jY", sub: 'video' },
    { type: 'video', label: "Trigonometric Functions: Sine, Cosine, Tangent, Cosecant, Secant, and Cotangent", url: "https://www.youtube.com/watch?v=cqIZue-plBI", sub: 'video' },
    { type: 'video', label: "The Easiest Way to Memorize the Trigonometric Unit Circle", url: "https://www.youtube.com/watch?v=75dMcyCUo2g", sub: 'video' },
    { type: 'video', label: "Basic Trigonometric Identities: Pythagorean Identities and Cofunction Identities", url: "https://www.youtube.com/watch?v=Ql7ducUjiG0", sub: 'video' },
    { type: 'video', label: "Graphing Trigonometric Functions", url: "https://www.youtube.com/watch?v=8oEjxGjAeQI", sub: 'video' },
    { type: 'video', label: "Inverse Trigonometric Functions", url: "https://www.youtube.com/watch?v=YXWKpgmLgHk", sub: 'video' },
    { type: 'video', label: "Verifying Trigonometric Identities", url: "https://www.youtube.com/watch?v=YYKGkYkKeMM", sub: 'video' },
    { type: 'video', label: "Formulas for Trigonometric Functions: Sum/Difference, Double/Half-Angle, Prod-to-Sum/Sum-to-Prod", url: "https://www.youtube.com/watch?v=0cB4MLhaCk0", sub: 'video' },
    { type: 'video', label: "Solving Trigonometric Equations", url: "https://www.youtube.com/watch?v=aq4b24jcZOc", sub: 'video' },
    { type: 'video', label: "The Law of Sines", url: "https://www.youtube.com/watch?v=MmfO1YgzmHI", sub: 'video' },
    { type: 'video', label: "The Law of Cosines", url: "https://www.youtube.com/watch?v=3wGQMyaWoLA", sub: 'video' },
    { type: 'video', label: "Polar Coordinates and Graphing Polar Equations", url: "https://www.youtube.com/watch?v=jwLUapqnwkk", sub: 'video' },
    { type: 'video', label: "Parametric Equations", url: "https://www.youtube.com/watch?v=QaN_3TytT_U", sub: 'video' },
    { type: 'video', label: "Introduction to Calculus: The Greeks, Newton, and Leibniz", url: "https://www.youtube.com/watch?v=rBVi_9qAKTU", sub: 'video' },
    { type: 'video', label: "Understanding Differentiation Part 1: The Slope of a Tangent Line", url: "https://www.youtube.com/watch?v=ktOYbZ8CpLA", sub: 'video' },
    { type: 'video', label: "Understanding Differentiation Part 2: Rates of Change", url: "https://www.youtube.com/watch?v=J27BZCX1OF8", sub: 'video' },
    { type: 'video', label: "Limits and Limit Laws in Calculus", url: "https://www.youtube.com/watch?v=wK8WuTEc0ns", sub: 'video' },
    { type: 'video', label: "What is a Derivative? Deriving the Power Rule", url: "https://www.youtube.com/watch?v=x3iEEDxrhyE", sub: 'video' },
    { type: 'video', label: "Derivatives of Polynomial Functions: Power Rule, Product Rule, and Quotient Rule", url: "https://www.youtube.com/watch?v=aL15O6rS9z0", sub: 'video' },
    { type: 'video', label: "Derivatives of Trigonometric Functions", url: "https://www.youtube.com/watch?v=_Zqcxbjzyxg", sub: 'video' },
    { type: 'video', label: "Derivatives of Composite Functions: The Chain Rule", url: "https://www.youtube.com/watch?v=_x1nCg2LfuA", sub: 'video' },
    { type: 'video', label: "Derivatives of Logarithmic and Exponential Functions", url: "https://www.youtube.com/watch?v=zjKMkbcbtHY", sub: 'video' },
    { type: 'video', label: "Implicit Differentiation", url: "https://www.youtube.com/watch?v=M0SMSWM2oZA", sub: 'video' },
    { type: 'video', label: "Higher Derivatives and Their Applications", url: "https://www.youtube.com/watch?v=zUDxgehxQqs", sub: 'video' },
    { type: 'video', label: "Related Rates in Calculus", url: "https://www.youtube.com/watch?v=j6I3EXiKB2A", sub: 'video' },
    { type: 'video', label: "Finding Local Maxima and Minima by Differentiation", url: "https://www.youtube.com/watch?v=pvLj1s7SOtk", sub: 'video' },
    { type: 'video', label: "Graphing Functions and Their Derivatives", url: "https://www.youtube.com/watch?v=dIY86WqvGjw", sub: 'video' },
    { type: 'video', label: "Optimization Problems in Calculus", url: "https://www.youtube.com/watch?v=q1U6AmIa_uQ", sub: 'video' },
    { type: 'video', label: "Understanding Limits and L'Hospital's Rule", url: "https://www.youtube.com/watch?v=g45quDrSA6g", sub: 'video' },
    { type: 'video', label: "What is Integration? Finding the Area Under a Curve", url: "https://www.youtube.com/watch?v=FsC3do74UIo", sub: 'video' },
    { type: 'video', label: "The Fundamental Theorem of Calculus: Redefining Integration", url: "https://www.youtube.com/watch?v=NLU9U8-wJrM", sub: 'video' },
    { type: 'video', label: "Properties of Integrals and Evaluating Definite Integrals", url: "https://www.youtube.com/watch?v=b0RJkIBhfEM", sub: 'video' },
    { type: 'video', label: "Evaluating Indefinite Integrals", url: "https://www.youtube.com/watch?v=-xHA2RjVkwY", sub: 'video' },
    { type: 'video', label: "Evaluating Integrals With Trigonometric Functions", url: "https://www.youtube.com/watch?v=7bJXbDqi9FE", sub: 'video' },
    { type: 'video', label: "Integration Using The Substitution Rule", url: "https://www.youtube.com/watch?v=sci1pls4Lc8", sub: 'video' },
    { type: 'video', label: "Integration By Parts", url: "https://www.youtube.com/watch?v=zNU8iK8sGD0", sub: 'video' },
    { type: 'video', label: "Integration By Trigonometric Substitution", url: "https://www.youtube.com/watch?v=t3rzxSgvZZk", sub: 'video' },
    { type: 'video', label: "Advanced Strategy for Integration in Calculus", url: "https://www.youtube.com/watch?v=8APOcBqbG-U", sub: 'video' },
    { type: 'video', label: "Evaluating Improper Integrals", url: "https://www.youtube.com/watch?v=0JOIhPfXnxc", sub: 'video' },
    { type: 'video', label: "Finding the Area Between Two Curves by Integration", url: "https://www.youtube.com/watch?v=xec6HTcn2M8", sub: 'video' },
    { type: 'video', label: "Calculating the Volume of a Solid of Revolution by Integration", url: "https://www.youtube.com/watch?v=QLHJl2_aM5Q", sub: 'video' },
    { type: 'video', label: "Calculating Volume by Cylindrical Shells", url: "https://www.youtube.com/watch?v=MNU5DT-CDrc", sub: 'video' },
    { type: 'video', label: "The Mean Value Theorem For Integrals: Average Value of a Function", url: "https://www.youtube.com/watch?v=56-JCZIkDVU", sub: 'video' },
    { type: 'video', label: "Convergence and Divergence: The Return of Sequences and Series", url: "https://www.youtube.com/watch?v=L-JqHo4-W4k", sub: 'video' },
    { type: 'video', label: "Estimating Sums Using the Integral Test and Comparison Test", url: "https://www.youtube.com/watch?v=Jtnxi9uM7yA", sub: 'video' },
    { type: 'video', label: "Alternating Series, Types of Convergence, and the Ratio Test", url: "https://www.youtube.com/watch?v=-Md4CEW0-zM", sub: 'video' },
    { type: 'video', label: "Power Series", url: "https://www.youtube.com/watch?v=OxVBT83x8oc", sub: 'video' },
    { type: 'video', label: "Taylor and Maclaurin Series", url: "https://www.youtube.com/watch?v=a58otkmkHtk", sub: 'video' },
    { type: 'video', label: "Hyperbolic Functions: Definitions, Identities, Derivatives, and Inverses", url: "https://www.youtube.com/watch?v=uMXcKY_w3w4", sub: 'video' },
    { type: 'video', label: "Three-Dimensional Coordinates and the Right-Hand Rule", url: "https://www.youtube.com/watch?v=5sJdfciNM20", sub: 'video' },
    { type: 'video', label: "Introduction to Vectors and Their Operations", url: "https://www.youtube.com/watch?v=KBSCMTYaH1s", sub: 'video' },
    { type: 'video', label: "The Vector Dot Product", url: "https://www.youtube.com/watch?v=0iNrGpwZwog", sub: 'video' },
    { type: 'video', label: "Introduction to Linear Algebra: Systems of Linear Equations", url: "https://www.youtube.com/watch?v=csgNflj69-Y", sub: 'video' },
    { type: 'video', label: "Understanding Matrices and Matrix Notation", url: "https://www.youtube.com/watch?v=y6bVhgmy2rw", sub: 'video' },
    { type: 'video', label: "Manipulating Matrices: Elementary Row Operations and Gauss-Jordan Elimination", url: "https://www.youtube.com/watch?v=T2Gtt8WygiU", sub: 'video' },
    { type: 'video', label: "Types of Matrices and Matrix Addition", url: "https://www.youtube.com/watch?v=biyQzy2yRUA", sub: 'video' },
    { type: 'video', label: "Matrix Multiplication and Associated Properties", url: "https://www.youtube.com/watch?v=P5GJJ02OG08", sub: 'video' },
    { type: 'video', label: "Evaluating the Determinant of a Matrix", url: "https://www.youtube.com/watch?v=CcbyMH3Noow", sub: 'video' },
    { type: 'video', label: "The Vector Cross Product", url: "https://www.youtube.com/watch?v=gPnWm-IXoAY", sub: 'video' },
    { type: 'video', label: "Inverse Matrices and Their Properties", url: "https://www.youtube.com/watch?v=kWorj5BBy9k", sub: 'video' },
    { type: 'video', label: "Solving Systems Using Cramer's Rule", url: "https://www.youtube.com/watch?v=RdLo-9jh2EM", sub: 'video' },
    { type: 'video', label: "Understanding Vector Spaces", url: "https://www.youtube.com/watch?v=EP2ghkO0lSk", sub: 'video' },
    { type: 'video', label: "Subspaces and Span", url: "https://www.youtube.com/watch?v=tM4TDL9Hj8U", sub: 'video' },
    { type: 'video', label: "Linear Independence", url: "https://www.youtube.com/watch?v=9kDpbZCK62Y", sub: 'video' },
    { type: 'video', label: "Basis and Dimension", url: "https://www.youtube.com/watch?v=4C9GKyfUQkc", sub: 'video' },
    { type: 'video', label: "Change of Basis", url: "https://www.youtube.com/watch?v=HZa1RwFHgwU", sub: 'video' },
    { type: 'video', label: "Linear Transformations on Vector Spaces", url: "https://www.youtube.com/watch?v=is1cg5yhdds", sub: 'video' },
    { type: 'video', label: "Image and Kernel", url: "https://www.youtube.com/watch?v=vyYrvhbDhW4", sub: 'video' },
    { type: 'video', label: "Orthogonality and Orthonormality", url: "https://www.youtube.com/watch?v=6nqMegdbxik", sub: 'video' },
    { type: 'video', label: "The Gram-Schmidt Process", url: "https://www.youtube.com/watch?v=zHbfZWZJTGc", sub: 'video' },
    { type: 'video', label: "Finding Eigenvalues and Eigenvectors", url: "https://www.youtube.com/watch?v=TQvxWaQnrqI", sub: 'video' },
    { type: 'video', label: "Diagonalization", url: "https://www.youtube.com/watch?v=WTLl03D4TNA", sub: 'video' },
    { type: 'video', label: "Complex, Hermitian, and Unitary Matrices", url: "https://www.youtube.com/watch?v=DUuTx2nbizM", sub: 'video' },
    { type: 'video', label: "Further Matrix Decompositions: LU, Cholesky, QR, and SVD", url: "https://www.youtube.com/watch?v=wHAJzemKQW4", sub: 'video' },
    { type: 'video', label: "Double and Triple Integrals", url: "https://www.youtube.com/watch?v=UubU3U2C8WM", sub: 'video' },
    { type: 'video', label: "Partial Derivatives and the Gradient of a Function", url: "https://www.youtube.com/watch?v=AXH9Xm6Rbfc", sub: 'video' },
    { type: 'video', label: "Vector Fields, Divergence, and Curl", url: "https://www.youtube.com/watch?v=2qxxd68fZng", sub: 'video' },
    { type: 'video', label: "Evaluating Line Integrals", url: "https://www.youtube.com/watch?v=Tz14rC0XvHI", sub: 'video' },
    { type: 'video', label: "Green's Theorem", url: "https://www.youtube.com/watch?v=kdTxN4E0vbo", sub: 'video' },
    { type: 'video', label: "Evaluating Surface Integrals", url: "https://www.youtube.com/watch?v=Gml1HT4y3_c", sub: 'video' },
    { type: 'video', label: "Stokes's Theorem", url: "https://www.youtube.com/watch?v=QS-zUSu-nxA", sub: 'video' },
    { type: 'video', label: "The Divergence Theorem", url: "https://www.youtube.com/watch?v=vZGvgru4TwE", sub: 'video' },
    { type: 'video', label: "Introduction to Differential Equations", url: "https://www.youtube.com/watch?v=QbkWlNf2Xtw", sub: 'video' },
    { type: 'video', label: "Classification of Differential Equations", url: "https://www.youtube.com/watch?v=lwed4VVYuHo", sub: 'video' },
    { type: 'video', label: "Separable First-Order Differential Equations", url: "https://www.youtube.com/watch?v=lbAX_LDjV5o", sub: 'video' },
    { type: 'video', label: "Linear First-Order Differential Equations", url: "https://www.youtube.com/watch?v=rO31HNxBedg", sub: 'video' },
    { type: 'video', label: "Exact First-Order Differential Equations", url: "https://www.youtube.com/watch?v=sJQIH4m0L_c", sub: 'video' },
    { type: 'video', label: "Homogeneous Differential Equations and Bernoulli Differential Equations", url: "https://www.youtube.com/watch?v=o1AHVHEEChA", sub: 'video' },
    { type: 'video', label: "Linear Second-Order Differential Equations Part 1: Homogeneous Case", url: "https://www.youtube.com/watch?v=MaZatB5UiwU", sub: 'video' },
    { type: 'video', label: "Linear Second-Order Differential Equations Part 2: Non-Homogeneous Differential Equations", url: "https://www.youtube.com/watch?v=bojO7brQtE8", sub: 'video' },
    { type: 'video', label: "Special Second-Order Differential Equations: Cauchy-Euler, Nonlinear, and More", url: "https://www.youtube.com/watch?v=fsjcKgXcTVg", sub: 'video' },
    { type: 'video', label: "Numerical Methods for Solving Differential Equations", url: "https://www.youtube.com/watch?v=A1JnGhaVJsQ", sub: 'video' },
    { type: 'video', label: "Power Series Solutions Part 1: Leibniz Method", url: "https://www.youtube.com/watch?v=g8iReAhrJcE", sub: 'video' },
    { type: 'video', label: "Power Series Solutions Part 2: Frobenius Method", url: "https://www.youtube.com/watch?v=58_qJyfVl-Y", sub: 'video' },
    { type: 'video', label: "Systems of Differential Equations Part 1: Modeling and Elimination", url: "https://www.youtube.com/watch?v=MW97ZFavZ0g", sub: 'video' },
    { type: 'video', label: "Systems of Differential Equations Part 2: Matrices and Stability", url: "https://www.youtube.com/watch?v=LrzyMJ8CS1g", sub: 'video' },
    { type: 'video', label: "Laplace Transforms Part 1: Solving Differential Equations", url: "https://www.youtube.com/watch?v=rrlBRs_etts", sub: 'video' },
    { type: 'video', label: "Laplace Transforms Part 2: Convolutions and LTI Systems", url: "https://www.youtube.com/watch?v=RecYAjxdcEg", sub: 'video' },
    { type: 'video', label: "Difference Equations and Z-Transforms", url: "https://www.youtube.com/watch?v=7eZ3p5RM89s", sub: 'video' },
    { type: 'video', label: "Introduction to Partial Differential Equations: Classification and Differential Operators", url: "https://www.youtube.com/watch?v=4Ou2FtsD8X8", sub: 'video' },
    { type: 'video', label: "Quasi-Linear First-Order Partial Differential Equations: Lagrange’s Method", url: "https://www.youtube.com/watch?v=LzMCBbxSMts", sub: 'video' },
    { type: 'video', label: "Laplace’s Equation: Separation of Variables", url: "https://www.youtube.com/watch?v=8jOqXM8OFh8", sub: 'video' },
    { type: 'video', label: "Fourier Series and Transforms Part 1: Concepts in Frequency Analysis", url: "https://www.youtube.com/watch?v=Eta7T0DoYu8", sub: 'video' },
    { type: 'video', label: "Fourier Series and Transforms Part 2: Power Spectra and K-Space", url: "https://www.youtube.com/watch?v=CO8NX6qnWko", sub: 'video' },
    { type: 'video', label: "The Wave Equation Part 1: Vibrations in 1D", url: "https://www.youtube.com/watch?v=ETowl5rNz40", sub: 'video' },
    { type: 'video', label: "The Wave Equation Part 2: Multidimensional Waves and Dispersion", url: "https://www.youtube.com/watch?v=BKhc7nJ4QAY", sub: 'video' },
    { type: 'video', label: "The Diffusion Equation Part 1: Separation of Variables", url: "https://www.youtube.com/watch?v=kRih2ctI3QM", sub: 'video' },
    { type: 'video', label: "The Diffusion Equation Part 2: Dimensional Analysis and Self-Similarity", url: "https://www.youtube.com/watch?v=mMVjgURyiB0", sub: 'video' },
    { type: 'video', label: "The Diffusion Equation Part 3: Green’s Functions", url: "https://www.youtube.com/watch?v=Ghobc7v1-Js", sub: 'video' },
  ],
};

